kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf-minio
data:
  nginx.conf: |-
    events {}
    http {
      server {
        listen 9000;
        server_name localhost;
        ignore_invalid_headers off;
        client_max_body_size 0;
        proxy_buffering off;
        location / {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Host minio:9000;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_connect_timeout 300;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          chunked_transfer_encoding off;
          proxy_pass http://minio:9000;
        } 
      }
    }
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
  name: nginx-minio
  namespace: 3187b2-tools
  labels:
    base-name: nginx-minio
    shared: 'true'
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nginx-minio
spec:
  output:
    to:
      kind: ImageStreamTag
      name: nginx-minio:latest
  postCommit: {}
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
  runPolicy: Serial
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 1
  source:
    dockerfile: |-
        FROM registry.redhat.io/rhscl/nginx-116-rhel7
        ADD ./nginx-conf/nginx.conf "${NGINX_CONF_PATH}"
        RUN chmod a+r "${NGINX_CONF_PATH}"
        EXPOSE 9000
        CMD nginx -g "daemon off;"
    configMaps:
      - configMap:
          name: nginx-conf-minio
        destinationDir: nginx-conf
        defaultMode: 664
  strategy:
    dockerStrategy: {}
  triggers:
  - type: ConfigChange
