kind: Template
apiVersion: v1
labels:
  template: web-template
metadata:
  name: web-dc
  creationTimestamp:
parameters:
  - name: TAG
    value: "dev"
    required: true
  - name: SITEMINDER_BASE_URL
    required: true
  - name: SSO_REALM_NAME
    required: true
  - name: SSO_CLIENT_ID
    required: true
  - name: SSO_BASE_URL
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: myra-web
      labels:
        name: myra-web
    spec:
      ports:
        - name: myra-web
          protocol: TCP
          port: 2015
          targetPort: 2015
      selector:
        name: myra-web
      type: ClusterIP
      sessionAffinity: None
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: myra-web
      labels:
        name: myra-web
        app: myra-web
    spec:
      replicas: 1
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - myra-web
          from:
            kind: ImageStreamTag
            name: "range-web-caddy:${TAG}"
            namespace: 3187b2-tools
        type: ImageChange
      test: false
      selector: 
        name: myra-web
      template:
        metadata:
          creationTimestamp:
          labels:
            name: myra-web
        spec:
          containers:
            - name: myra-web
              image: ''
              ports:
                - containerPort: 2015
                  protocol: TCP
              resources:
                limits:
                  cpu: 100m
                  memory: 256Mi
                requests:
                  cpu: 10m
                  memory: 160Mi
              env:
                - name: SSO_BASE_URL
                  value: '${SSO_BASE_URL}'
                - name: SITEMINDER_BASE_URL
                  value: '${SITEMINDER_BASE_URL}'
                - name: SSO_REALM_NAME
                  value: '${SSO_REALM_NAME}'
                - name: SSO_CLIENT_ID
                  value: '${SSO_CLIENT_ID}'
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /index.html
                  port: 2015
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 3
              imagePullPolicy: Always
              securityContext:
                capabilities: {}
                privileged: false
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
    
