apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  labels:
    build: range-web
  name: range-web
parameters:
- name: NAME
  displayName: Name
  description: A suffix appended to all objects
  required: true
  value: range-web
- name: SUFFIX
  displayName: Name Suffix
  description: A suffix appended to all objects
  required: true
  value: dev
- name: VERSION
  required: true
  value: 'latest'
- name: SOURCE_CONTEXT_DIR
  required: true
  value: "./"
- name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/plasticviking/range-web
- name: SOURCE_REPOSITORY_REF
  required: false
  value: dev
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    creationTimestamp: null
    annotations:
      description: Built react image
    labels:
      shared: 'true'
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: "${NAME}"
    creationTimestamp: 
    labels: {}
    annotations: {}
  spec:
    nodeSelector: 
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:${VERSION}"
    postCommit: {}
    resources:
      limits:
        cpu: 2
        memory: 6Gi
      requests:
        cpu: 2
        memory: 6Gi
    runPolicy: Serial
    source:
      contextDir: "${SOURCE_CONTEXT_DIR}"
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: node:10
      type: Docker
    failedBuildsHistoryLimit: 2
    successfulBuildsHistoryLimit: 2
    triggers:
    - type: ConfigChange
    - type: ImageChange

