kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
  name: caddy
  namespace: 3187b2-tools
  labels:
    base-name: caddy
    shared: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '2-alpine'
      annotations: null
      from:
        kind: DockerImage
        name: >-
          docker-remote.artifacts.developer.gov.bc.ca/caddy/caddy:2-alpine
      importPolicy: {}
      referencePolicy:
        type: Local