kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
  name: minio
  namespace: 3187b2-tools
  labels:
    base-name: minio
    shared: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 'latest'
      annotations: null
      from:
        kind: DockerImage
        name: >-
          docker-remote.artifacts.developer.gov.bc.ca/minio/minio:latest
      importPolicy: {}
      referencePolicy:
        type: Local