name: Openshift deployer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install oc client v3.11.0
      run: |
        cd $HOME
        curl -LO https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
        tar -xf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
        cd openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit
        chmod +x oc
        echo "::set-env name=PATH_TO_OC::$PATH:$(pwd)"
    - name: Login to openshift
      run: |
        cd $HOME
        export PATH=$PATH_TO_OC
        oc login https://console.pathfinder.gov.bc.ca:8443 --token=${{ secrets.sa_token }}
    - name: Build image
      env:
        APP_NAME: range-myra-web-ghactiontest
        IMAGE_STREAM_NAME: $APP_NAME
        GIT_BRANCH_NAME: ${GITHUB_REF##*/}
      run: | 
        cd $HOME
        export PATH=$PATH_TO_OC
        #TODO: cache session token in secret?
        oc login https://console.pathfinder.gov.bc.ca:8443 --token=${{ secrets.sa_token }}
        cd $GITHUB_WORKSPACE
        oc start-build --from-repo=./range-web
