name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 8.17.0
      - run: npm run test:e2e:server:start
      - name: Cypress run
        uses: cypress-io/github-action@v1
        env:
          auth_base_url: 'https://sso-dev.pathfinder.gov.bc.ca/auth'
          auth_realm: range
          auth_client_id: myrangebc
          app_base_url: http://localhost:3000
          range_officer_username: ${{ secrets.RANGE_OFFICER_USERNAME }}
          range_officer_password: ${{ secrets.RANGE_OFFICER_PASSWORD }}
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 500
