name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node8.9.3-chrome73
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run test:e2e:server:start && npm start
          wait-on: 'http://localhost:3000'
